### PR TITLE
Update jarjar with asm-7.0 for Java 11

### PR DESCRIPTION
**Pull request by alanpincus**
This commit includes a script and patch that will do the following:
- Clone github.com/google/jarjar
- Download asm-7.0.jar using curl
- Download asm-commons-7.0.jar using curl
- Delete the older asm jars (their presence would break ant build)
- Patch jarjar code specifying new asm jars
- Run ant build script

Requirements: git, curl, Java 11, ant

Directions:
- Place script and patch in same directory
- Invoke script
- Retrieve newly generated jarjar/dist/jarjar-11.jar
- Modify java_deps/jars.mk when ready to use the new jar

### CODE REVIEW

**Comment by alanpincus** [comment]
The email I used for my commit did not match the email of my CLA. I will try again using the correct email.

**Comment by tomball** [comment]
Don't bother with a pull request, as Antonio separately updated this earlier this week. I'll do a push from our internal repository so you have his change.

**Comment by alanpincus** [comment]
Thanks for the offer, but there's no point in your pushing something specially for me as I would not be able to integrate it right away.

I've long felt that I should contribute something to the J2ObjC project, and I thought that I finally had a timely fix for you. I'm now able to translate OpenJDK 10 with my version of J2ObjC, but it's not obvious how I can contribute to J2ObjC given the differences in our codebases. The jarjar fix, with fewer dependencies, seemed like a good opportunity. I could have done it sooner, but until recently I didn't think you had interest yet in Java 11.

Thanks again for the J2ObjC project, and please let me know if there's any way I can help.
Alan

**Comment by tomball** [comment]
It's awesome that you want to contribute, and I didn't mean to dampen your enthusiasm. Antonio has been focused on updating to Java 11 since it's a LTS release. We won't support new API right away, though, as the jre_emul library is a fork of Android's libcore library.

**Pull request closed without merging**
