### PR TITLE
Updating SubjectTest

### PR DESCRIPTION
**Pull request by albertomisail**
Test did not use to work because of serialization issues. Now that serialization was updated, test work

### CODE REVIEW

**Comment by tomball** [comment]
I think a bug should be filed and the comments updated, as both tests still fail:
```
There were 2 failures:
1) testSerialization_nullPrincipalsAllowed(org.apache.harmony.tests.javax.security.auth.SubjectTest)
java.io.NotSerializableException: java.lang.Object
        at 0x0000000100bf0fb8 java.lang.Throwable.nativeFillInStackTrace() + 24
        at 0x0000000100bbd600 java.lang.Exception.<init>() + 32
        at 0x0000000100b623d0 java.io.IOException.<init>() + 32
        at 0x0000000100b92670 java.io.ObjectStreamException.<init>() + 32
        at 0x0000000100b65200 java.io.NotSerializableException.<init>() + 32
        at 0x0000000100b77824 java.io.ObjectOutputStream.writeObject0() + 1892
        at 0x0000000100b7809a java.io.ObjectOutputStream.defaultWriteFields() + 1098
        at 0x0000000100b77c22 java.io.ObjectOutputStream.defaultWriteObject() + 194
        at 0x0000000100cf5f8d java.util.Collections$SynchronizedCollection.writeObject() + 109
        at 0x0000000100cf5f11 java.util.Collections$SynchronizedCollection.writeObject() + 33
        at 0x0000000101865cbc java.lang.reflect.Method.invoke:object:() + 44
        at 0x00000001018657c5 java.lang.reflect.Method.invoke() + 757
        at 0x0000000100b86c14 java.io.ObjectStreamClass.invokeWriteObject() + 196
        at 0x0000000100b7b8dc java.io.ObjectOutputStream.writeSerialData() + 668
        at 0x0000000100b7b2e9 java.io.ObjectOutputStream.writeOrdinaryObject() + 585
        at 0x0000000100b777f7 java.io.ObjectOutputStream.writeObject0() + 1847
        at 0x0000000100b7809a java.io.ObjectOutputStream.defaultWriteFields() + 1098
        at 0x0000000100b77c22 java.io.ObjectOutputStream.defaultWriteObject() + 194
        at 0x0000000101004f2d javax.security.auth.Subject.writeObject() + 109
        at 0x0000000101004eb1 javax.security.auth.Subject.writeObject() + 33
        at 0x0000000101865cbc java.lang.reflect.Method.invoke:object:() + 44
        at 0x00000001018657c5 java.lang.reflect.Method.invoke() + 757
        at 0x0000000100b86c14 java.io.ObjectStreamClass.invokeWriteObject() + 196
        at 0x0000000100b7b8dc java.io.ObjectOutputStream.writeSerialData() + 668
        at 0x0000000100b7b2e9 java.io.ObjectOutputStream.writeOrdinaryObject() + 585
        at 0x0000000100b777f7 java.io.ObjectOutputStream.writeObject0() + 1847
        at 0x0000000100b7701e java.io.ObjectOutputStream.writeObject() + 78
        at 0x0000000101998a6f org.apache.harmony.testframework.serialization.SerializationTest.putObjectToStream() + 95
        at 0x0000000101999c0f org.apache.harmony.testframework.serialization.SerializationTest.copySerializable() + 79
        at 0x0000000101999514 org.apache.harmony.testframework.serialization.SerializationTest.verifySelf() + 212
        at 0x0000000101999407 org.apache.harmony.testframework.serialization.SerializationTest.verifySelf() + 87
        at 0x00000001027f0567 org.apache.harmony.tests.javax.security.auth.SubjectTest.testSerialization_nullPrincipalsAllowed() + 199
        at 0x0000000101865cbc java.lang.reflect.Method.invoke:object:() + 44
        at 0x00000001018657c5 java.lang.reflect.Method.invoke() + 757
        at 0x000000010189a875 junit.framework.TestCase.runTest() + 517
        at 0x000000010189a4f5 junit.framework.TestCase.runBare() + 69
        at 0x000000010189de1e junit.framework.TestResult$.protect() + 78
        at 0x000000010189d4e0 junit.framework.TestResult.runProtected() + 144
        at 0x000000010189d383 junit.framework.TestResult.run() + 99
        at 0x000000010189a4a2 junit.framework.TestCase.run() + 82
        at 0x000000010189f81b junit.framework.TestSuite.runTest() + 75
        at 0x000000010189f72f junit.framework.TestSuite.run() + 463
        at 0x00000001018c77dc org.junit.internal.runners.JUnit38ClassRunner.run() + 140
        at 0x00000001018ec586 org.junit.runners.Suite.runChild() + 86
        at 0x00000001018eba68 org.junit.runners.ParentRunner$.run() + 56
        at 0x00000001018eb763 org.junit.runners.ParentRunner$.schedule() + 67
        at 0x00000001018ea31b org.junit.runners.ParentRunner.runChildren() + 411
        at 0x00000001018eb8a3 org.junit.runners.ParentRunner$.evaluate() + 51
        at 0x00000001018eab40 org.junit.runners.ParentRunner.run() + 240
        at 0x00000001018ec586 org.junit.runners.Suite.runChild() + 86
        at 0x00000001018eba68 org.junit.runners.ParentRunner$.run() + 56
        at 0x00000001018eb763 org.junit.runners.ParentRunner$.schedule() + 67
        at 0x00000001018ea31b org.junit.runners.ParentRunner.runChildren() + 411
        at 0x00000001018eb8a3 org.junit.runners.ParentRunner$.evaluate() + 51
        at 0x00000001018eab40 org.junit.runners.ParentRunner.run() + 240
        at 0x00000001018dd299 org.junit.runner.JUnitCore.run() + 281
        at 0x00000001018dd11d org.junit.runner.JUnitCore.run() + 109
        at 0x00000001018dd044 org.junit.runner.JUnitCore.run() + 68
        at 0x00000001018dcd8c org.junit.runner.JUnitCore.runMain() + 1164
        at 0x00000001018dc795 org.junit.runner.JUnitCore.runMainAndExit() + 37
        at 0x00000001018dc72d org.junit.runner.JUnitCore.main() + 29
        at 0x00000001018dc6fd org.junit.runner.JUnitCore.main() + 29
2) testSerializationSelf(org.apache.harmony.tests.javax.security.auth.SubjectTest)
java.io.NotSerializableException: java.lang.Object
        at 0x0000000100bf0fb8 java.lang.Throwable.nativeFillInStackTrace() + 24
        at 0x0000000100bbd600 java.lang.Exception.<init>() + 32
        at 0x0000000100b623d0 java.io.IOException.<init>() + 32
        at 0x0000000100b92670 java.io.ObjectStreamException.<init>() + 32
        at 0x0000000100b65200 java.io.NotSerializableException.<init>() + 32
        at 0x0000000100b77824 java.io.ObjectOutputStream.writeObject0() + 1892
        at 0x0000000100b7809a java.io.ObjectOutputStream.defaultWriteFields() + 1098
        at 0x0000000100b77c22 java.io.ObjectOutputStream.defaultWriteObject() + 194
        at 0x0000000100cf5f8d java.util.Collections$SynchronizedCollection.writeObject() + 109
        at 0x0000000100cf5f11 java.util.Collections$SynchronizedCollection.writeObject() + 33
        at 0x0000000101865cbc java.lang.reflect.Method.invoke:object:() + 44
        at 0x00000001018657c5 java.lang.reflect.Method.invoke() + 757
        at 0x0000000100b86c14 java.io.ObjectStreamClass.invokeWriteObject() + 196
        at 0x0000000100b7b8dc java.io.ObjectOutputStream.writeSerialData() + 668
        at 0x0000000100b7b2e9 java.io.ObjectOutputStream.writeOrdinaryObject() + 585
        at 0x0000000100b777f7 java.io.ObjectOutputStream.writeObject0() + 1847
        at 0x0000000100b7809a java.io.ObjectOutputStream.defaultWriteFields() + 1098
        at 0x0000000100b77c22 java.io.ObjectOutputStream.defaultWriteObject() + 194
        at 0x0000000101004f2d javax.security.auth.Subject.writeObject() + 109
        at 0x0000000101004eb1 javax.security.auth.Subject.writeObject() + 33
        at 0x0000000101865cbc java.lang.reflect.Method.invoke:object:() + 44
        at 0x00000001018657c5 java.lang.reflect.Method.invoke() + 757
        at 0x0000000100b86c14 java.io.ObjectStreamClass.invokeWriteObject() + 196
        at 0x0000000100b7b8dc java.io.ObjectOutputStream.writeSerialData() + 668
        at 0x0000000100b7b2e9 java.io.ObjectOutputStream.writeOrdinaryObject() + 585
        at 0x0000000100b777f7 java.io.ObjectOutputStream.writeObject0() + 1847
        at 0x0000000100b7701e java.io.ObjectOutputStream.writeObject() + 78
        at 0x0000000101998a6f org.apache.harmony.testframework.serialization.SerializationTest.putObjectToStream() + 95
        at 0x0000000101999c0f org.apache.harmony.testframework.serialization.SerializationTest.copySerializable() + 79
        at 0x0000000101999514 org.apache.harmony.testframework.serialization.SerializationTest.verifySelf() + 212
        at 0x00000001019981df org.apache.harmony.testframework.serialization.SerializationTest.verifySelf() + 271
        at 0x0000000101998322 org.apache.harmony.testframework.serialization.SerializationTest.verifySelf() + 306
        at 0x00000001027f0371 org.apache.harmony.tests.javax.security.auth.SubjectTest.testSerializationSelf() + 33
        at 0x0000000101865cbc java.lang.reflect.Method.invoke:object:() + 44
        at 0x00000001018657c5 java.lang.reflect.Method.invoke() + 757
        at 0x000000010189a875 junit.framework.TestCase.runTest() + 517
        at 0x000000010189a4f5 junit.framework.TestCase.runBare() + 69
        at 0x000000010189de1e junit.framework.TestResult$.protect() + 78
        at 0x000000010189d4e0 junit.framework.TestResult.runProtected() + 144
        at 0x000000010189d383 junit.framework.TestResult.run() + 99
        at 0x000000010189a4a2 junit.framework.TestCase.run() + 82
        at 0x000000010189f81b junit.framework.TestSuite.runTest() + 75
        at 0x000000010189f72f junit.framework.TestSuite.run() + 463
        at 0x00000001018c77dc org.junit.internal.runners.JUnit38ClassRunner.run() + 140
        at 0x00000001018ec586 org.junit.runners.Suite.runChild() + 86
        at 0x00000001018eba68 org.junit.runners.ParentRunner$.run() + 56
        at 0x00000001018eb763 org.junit.runners.ParentRunner$.schedule() + 67
        at 0x00000001018ea31b org.junit.runners.ParentRunner.runChildren() + 411
        at 0x00000001018eb8a3 org.junit.runners.ParentRunner$.evaluate() + 51
        at 0x00000001018eab40 org.junit.runners.ParentRunner.run() + 240
        at 0x00000001018ec586 org.junit.runners.Suite.runChild() + 86
        at 0x00000001018eba68 org.junit.runners.ParentRunner$.run() + 56
        at 0x00000001018eb763 org.junit.runners.ParentRunner$.schedule() + 67
        at 0x00000001018ea31b org.junit.runners.ParentRunner.runChildren() + 411
        at 0x00000001018eb8a3 org.junit.runners.ParentRunner$.evaluate() + 51
        at 0x00000001018eab40 org.junit.runners.ParentRunner.run() + 240
        at 0x00000001018dd299 org.junit.runner.JUnitCore.run() + 281
        at 0x00000001018dd11d org.junit.runner.JUnitCore.run() + 109
        at 0x00000001018dd044 org.junit.runner.JUnitCore.run() + 68
        at 0x00000001018dcd8c org.junit.runner.JUnitCore.runMain() + 1164
        at 0x00000001018dc795 org.junit.runner.JUnitCore.runMainAndExit() + 37
        at 0x00000001018dc72d org.junit.runner.JUnitCore.main() + 29
        at 0x00000001018dc6fd org.junit.runner.JUnitCore.main() + 29
```

**Comment by albertomisail** [comment]
I think they passed in my local build but let me confirm

**Comment by tomball** [comment]
The issue is that a Collections.SerializedSet has an `Object mutex` field, and Object isn't serializable. I'll see if it's fixed in Java 11, and if so, we can port the patch (it's either in ObjectOutputStream or Collections). However, I suspect these tests are disabled in the libcore build, and so this shouldn't be a high priority.

**Comment by albertomisail** [comment]
Fixed

**Pull request merged**
