### PR TITLE
Add watch sim for arm64

### PR DESCRIPTION
**Pull request by hohteri**

### CODE REVIEW

**Comment by tomball** [comment]
Thanks for contributing this. Please sync your repository to the latest google/j2objc master branch, then resolve any conflicts.

**Comment by tomball** [comment]
Friendly ping, @hohteri: would you please resolve these conflicting files? It should be straightforward for me to do, but since I don't have an M1 Mac, I can't verify this PR will build after resolving them.

**Comment by hohteri** [comment]
Please note that I let it run for 2 hours to build it fully and it failed with `unzip:  cannot find or open ../../java_deps/build_result/truth-1.1.2-sources.jar, ../../java_deps/build_result/truth-1.1.2-sources.jar.zip or ../../java_deps/build_result/truth-1.1.2-sources.jar.ZIP.
make[1]: *** [/Users/hohteri/Projects/j2objc/testing/truth/build_result/.extracted] Error 9`

**Review by tomball — APPROVED** [review]
I'll separately investigate the truth library failure. It was only recently added to the distribution (more of the tests we use require it), and I can believe there may be an issue with its build, independent of this PR.

**Comment by tomball** [comment]
FYI, we don't directly merge PRs into this repository any more. Now PRs get approved, which triggers them getting imported into our internal repository, where once that's approved, causes this repository to get the change. It takes a day or two, but the extra review and continuous integration build results in fewer errors being committed.

**Comment by tomball** [comment]
Thanks for your contribution!

**Pull request merged**
