### PR TITLE
Object*Stream update

### PR DESCRIPTION
**Pull request by anjulij**
- Removed io/EmmulatedFields.java, io/EmulatedFieldsForLoading.java, and io/EmulatedFieldsForDumping.java. Removed corresponding jre_sources.mk entries.
- Added io/Bits.java and its corresponding jre_sources.mk entry for use in io/ObjectStreamClass.java. Removed native/Bits.m and its corresponding jre_sources.mk entry
- Updated io/ObjectInputStream.java and io/ObjectOutputStream.java to current android source which uses OpenJDK instead of Apache Harmony. Added native implementation of both
- Updated io/ObjectStreamField.java to current android source which uses OpenJDK instead of Apache Harmony
- Updated io/ObjectStreamClass.java to current android sources which uses OpenJDK instead of Apache Harmony. Removed methods unsupported by J2ObjC. Implemented native newInstance(). Fixed ObjectStreamClass dynamic loading of MessageDigest.

### CODE REVIEW

**Comment by anjulij** [comment]
@googlebot I consent.

**Comment by tomball** [comment]
I consent (stupid bot!).

**Comment by tomball** [comment]
Hey @googlebot, check this again!

**Comment by anjulij** [comment]
@googlebot I consent.

**Comment by tomball** [comment]
Please scan again, @googlebot.

**Comment by tomball** [comment]
@googlebot I consent

**Comment by tomball** [comment]
Copybara merged #1413 in [bebc43d](https://github.com/google/j2objc/commit/bebc43d58660ce291fc93cb53b62bd1d489bb6ef)  but didn't close this PR.

**Pull request closed without merging**
