### PR TITLE
Add /usr/local/bin/ to PATH for mvn from homebrew

### PR DESCRIPTION
**Pull request by brunobowden**
Feel free to solve this in an alternative manner if something else is more appropriate

### CODE REVIEW

**Comment by tomball** [comment]
This delta finally merged -- the issue was that the JreEmulation project needed an overhaul first.

**Comment by brunobowden** [comment]
@tomball - did you want to add "/opt/local/bin" as well since you mentioned it before?

**Comment by tomball** [comment]
Already done:

grep usr/local/bin
third_party/java_src/j2objc/jre_emul/JreEmulation.xcodeproj/project.pbxproj
buildArgumentsString = "-c \"export
PATH=$PATH:/usr/local/bin:/opt/local/bin; if [ x$ACTION == xclean ]; then
make clean; else make -j4 dist; fi\"";

**Comment by brunobowden** [comment]
Wonderful

**Pull request closed without merging**
