### PR TITLE
Add support for arm64_32 architecture in watchOS binaries

### PR DESCRIPTION
**Pull request by gianlucabertani**
This mini pull request adds the arm64_32 architecture to the fat binaries for watchOS.

Build has been tested: completes successfully, and binaries do contain i386, armv7k and arm64_32 code segments. New binaries fix compilation issues such as "missing arm64_32 architecture" when building watchOS extensions on Xcode 10.x.

See also issue #1013.

### CODE REVIEW

**Comment by gianlucabertani** [comment]
The CLA is signed (but with my corporate e-mail address).

**Comment by antonio-cortes-perez** [comment]
Thanks for your report and pull request! I'll give it a try and merge it once the automated CLA check passes.

**Comment by gianlucabertani** [comment]
BTW, this is not my first contribution, see PR #738. Don't know why the CLA check failed.

**Comment by antonio-cortes-perez** [comment]
It's weird, I do not know how the CLA check works. It could be that it expires after certain time or when the clauses in the agreement are updated. When you have a chance, could you please check the links in this comment? https://github.com/google/j2objc/pull/1014#issuecomment-440062513
Thanks!

**Comment by gianlucabertani** [comment]
I signed it again as an individual. CLA checks should pass now.

**Comment by gianlucabertani** [comment]
Thank you for this great project!

**Pull request merged**
